**Dating in college has never been easy. But today, with everyone texting with emoji and navigating an increasingly fluid sexuality, it can seem almost impossible. Charlotte Lieberman, a recent Harvard grad, takes on what’s wrong with love on campus.**

It is 9 p.m. on a November Saturday at Harvard. I am sitting in my dorm, having just applied Sally Hansen leopard-print press-on nails and wearing a $24 chiffon dress from Forever 21 that my sister told me “looks really expensive.” I am waiting to hear from a nerdy but cute guy I’ll call Nate*, whom I know from class. He asked me out last night. Well, sort of.

We were at a party when he approached me and said, “Hey, Charlotte. Maybe we’ll cross paths tomorrow night? I’ll text you.” I assumed the maybe and his general passivity were just ways to avoid feeling insecure about showing interest. After all, we are millennials and old-fashioned courtship no longer exists. At least not according to New York Times reporter Alex Williams, who argues in his article “The End of Courtship?” that millennials are “a generation confused about how to land a boyfriend or girlfriend.”

Williams is not the only one thinking about millennials and our potentially hopeless futures for finding love. I read with interest the numerous other articles, books, and blog posts about the “me, me, me generation” (as Time’s Joel Stein calls us), our rejection of chivalry, and our hookup culture — which is supposedly the downfall of college dating. I’m lured in by these trend pieces and their sexy headlines and consistently let down by their conclusions about my generation’s moral depravity, narcissism, and distaste for true love.

Not that it’s all BS. College dating isn’t all rainbows and sparkles. I didn’t walk away from my conversation with Nate expecting a bouquet of roses to follow. Instead, I armed myself with a blasé smile and answered, “Just text me to let me know what’s up. At some point after dinner-ish time?” Sure, I wanted a plan for when we were supposed to hang out but felt I needed to meet Nate on his level of vagueness. He gave a feeble nod and winked. It’s a date-ish, I thought.

Nate never wrote or called me that night, even after I texted him at 11 p.m. to ask "What's up" (no question mark — that would seem too desperate). Overdressed for the nonoccasion, I quelled my frustration with Trader Joe's maple clusters and reruns of Mad Men. The next morning, I texted Nate again — this time to acknowledge our failed plan: “Bummer about last night. Maybe another time?” No answer. When I saw him in class, he glanced away whenever we made eye contact. The avoidance — and occasional tight-lipped smiles — continued through the fall semester.

In March, I saw Nate at a party. He was drunk and apologized for hurting my feelings that night in the fall. “It’s fine!” I told him. “If anything, it’s just like, confusion, you know? As to why you got weird.” But Nate didn’t acknowledge his weirdness. Instead, he said that he thought I was “really attractive and bright” but he just hadn’t been interested in dating me.

Wait, who said anything about dating?! I thought to myself, annoyed. I simply wanted to hang out. But I didn’t have the energy to tell Nate that I was sick of his (and many other guys’) assumption that women spend their days plotting to pin down a man and that ignoring me wasn’t the kindest way to tell me he didn’t want to lead me on. So to avoid seeming too emotional, crazy, or any of the related stereotypes commonly pegged on women, I followed Nate’s immature lead: I walked away to get a beer and dance with my friends. So long, Nate.

This anecdote sums up a pattern I have experienced, observed, and heard about from almost all my college-age friends. The culture of campus dating is broken...or at least broken-ish. And I think it’s because we are a generation frightened of letting ourselves be emotionally vulnerable, addicted to communicating by text, and as a result, neglecting to treat each other with respect. So, how do we fix it?

#Hookup Culture is Not the Problem

First, let me rule out the buzz phrase hookup culture as a cause of our broken social scene. Hookup culture isn’t new. Sex is sex. College kids do it, have always done it, and will always do it, whether they’re in relationships or not. Casual sex is not the evil root of all our problems.

Unlike Caitlin Flanagan, author of Girl Land, I don’t yearn for the days of male chivalry. Then again, I’m disappointed by the other side of the hookup-culture debate, helmed by Hanna Rosin, author of The End of Men: And the Rise of Women. Rosin argues that hookup culture marks the empowerment of career-minded college women. It does seem that, now more than ever, women are ruling the school. We account for 57 percent of college enrollment in the U.S. and earn 60 percent of bachelor’s degrees, according to the National Center for Education Statistics, and this gender gap will continue to increase through 2020, the center predicts. But I’m still not comfortable with Rosin’s assertion that “feminist progress...depends on the existence of hookup culture.”

The career-focused and hyper-confident types of women upon whom Rosin focuses her argument reappeared in Kate Taylor’s July 2013 New York Times feature “She Can Play That Game Too.” In Taylor’s story, female students at Penn speak proudly about the “cost-benefit” analyses and “low-investment costs” of hooking up as compared to being in committed relationships. In theory, hookup culture empowers millennial women with the time and space to focus on our ambitious goals while still giving us the benefit of sexual experience, right?

I’m not so sure. As Maddie, my 22-year-old friend from Harvard (who, FYI, graduated with highest honors and is now at Yale Law School), puts it: “The ‘I don’t have time for dating’ argument is bullshit. As someone who has done both the dating and the casual-sex thing, hookups are much more draining of my emotional faculties...and actually, my time.”

Sure, many women enjoy casual sex — and that’s a valuable thing to point out given how old-fashioned society’s attitudes on romance can still be. The fact that women now invest in their ambitions rather than spend college looking for a husband (the old MRS degree) is a good thing. But Rosin doesn’t acknowledge that there is still sexism lurking beneath her assertion that women are now able to “keep pace with the boys.” Is the fact that some college women are now approaching casual sex with a stereotypically masculine attitude a sign of progress? No.

#Whoever Cares Less Wins

In his book Guyland, Michael Kimmel, PhD, explores the world of young men between adolescence and adulthood, including the college years. The first rule of what he calls Guyland’s culture of silence is that “you can express no fears, no doubts, no vulnerabilities.” Sure, feminism appears to be all the rage on campus, but many self-identified feminists — myself included — equate liberation with the freedom to act “masculine” (not being oversensitive or appearing thin-skinned).

Lisa Wade, PhD, a professor of sociology at Occidental College who studies gender roles in college dating, explains that we’re now seeing a hookup culture in which young people exhibit a preference for behaviors coded masculine over ones that are coded feminine. Most of my peers would say “You go, girl” to a young woman who is career-focused, athletically competitive, or interested in casual sex. Yet no one ever says “You go, boy!” when a guy “feels liberated enough to learn to knit, decide to be a stay-at-home dad, or learn ballet,” Wade says. Men and women are both partaking in Guyland’s culture of silence on college campuses, which results in what Wade calls the whoever-cares-less-wins dynamic. We all know it: When the person you hooked up with the night before walks toward you in the dining hall, you try not to look excited... and maybe even look away. When it comes to dating, it always feels like the person who cares less ends up winning.

When I asked my friend Alix, 22, also a recent Harvard grad, what the biggest struggle of college dating was for her, she didn’t hesitate before saying: “I am terrified of getting emotionally overinvested when I’m seeing a guy. I’m scared of being totally honest.” I’ve felt this way too. I could’ve told Nate that I thought we had a plan...or I was hurt when he ditched me...or I was annoyed when he decided to pull away after wrongly assuming I’d wanted to make him my boyfriend. But I didn’t. Instead, we ignored each other, knowing that whoever cares less wins. As my guy friend Parker, 22, explains, “I think people in college are embarrassed to want to be in a relationship, as though wanting commitment makes them some regressive ’50s Stepford person. And when someone does want a relationship, they downplay it. This leads to awkward, sub-text-laden conversations, of which I’ve been on both sides.”

The great irony is that no one seems to enjoy playing the whoever-cares-less-wins game. Between 2005 and 2011, New York University sociologist Paula England, PhD, conducted an online survey in which she compiled data from more than 20,000 students at 21 colleges and universities throughout the United States. Her data showed that 61 percent of men hoped a hookup would turn into something more and 68 percent of women hoped for more — almost the same! We’re all trying so hard not to care, and nobody’s benefiting.

#Who Has The Power

When it comes to college dating today, guys seem to be in a position of power, calling the shots on sex and romance — partly because they’re especially good at playing the who-ever-cares-less game and partly because of the male-dominated places women go to meet straight guys on campus. At Harvard, these are the eight all-male social groups called final clubs. Each club owns a beautiful mansion in Harvard Square, and many of them have existed for a century or more. While five female final clubs also exist, they were founded in the 1990s or later, and most of them don’t have the impressive real estate or alumni funds the male clubs do.

Final clubs give their exclusive list of male members a sweet pad where they can hang out, study, smoke cigars, eat prosciutto and melon after class, and pregame with top-shelf liquor. But more important, they are known on campus as places where people party on the weekend. Women (but not non- member men) — and especially freshman girls — can choose to line up outside each house and be deemed worthy of entrance if the members consider them hot enough. In the words of a fellow Harvard girl, “These dweeby Harvard dudes are picking from a group of awesome women. This creates a sense of competition, making it so that women often go further sexually than they’re comfortable with because, you know, ‘He could’ve had anyone.’” My friends on other campuses around the country, especially ones where women outnumber men, agree that guys seem to hold the dating power. And even the brightest, most ambitious college women are permitting them to dominate the sexual culture.

#Digital Dating

Add to the mix that college-age kids depend heavily on the immediacy of texts, Gchats, and Instagram to talk with each other. This has produced a generation-wide handicap: a resistance to communicating with fully developed thoughts and emotions. (If a guy sends me a text that says “<3," does that carry the same weight as his staring into my eyes and saying "I love you"? I don't think so.)

Even though we are all addicted to texting, it’s still a huge source of anxiety when it comes to dating. Take Haley, 24, a University of Michigan grad who told me about how she and her college roommates had an in-depth conversation about how to respond to a guy’s text, creating rules for how long to wait before texting a guy back. “It can’t be 10 minutes on the dot, because then it is obvious you were waiting. It should be longer than 15 minutes to show you’re not desperate but within the 45-minute window if you are trying to lay groundwork for that evening,” she says. Guys agonize over texts too, especially about coming across as overly interested. Josh, 22, who goes to The New School, in New York City, admits, “I try to use exclamation points a lot but usually put a space between the last word and the ! to tone down the enthusiasm.”

What’s worse, the informality of texts and the like seems to have seeped into the way we think about basic respect in relationships. At the beginning of her senior spring semester, Sophie, 24, a beautiful Harvard math whiz now working as a researcher in Northern California, drunkenly met Charlie, to whom she’d been introduced by her friend Dan, Charlie’s roommate. They began going on regular dates to movies, museums, and dinner. In Sophie’s words, “It wasn’t clear how serious it was, but it was fun.”

Sophie and Charlie’s dynamic of not-clear-but-fun continued for about six months, until it ended suddenly. Sophie explains: “I texted Charlie to hang out one day as I normally would and never got a response. I waited the classic two days...and still no response. Then another day, then another. Radio silence. When I ran into him at a party a month later, he just walked up and asked, ‘How are you?’” Sophie was aware enough of her anger that she answered accordingly: “Are you fucking kidding me?” Charlie’s response: “Well, we never really knew what we were.”

Charlie must’ve assumed that the lack of official commitment in their six-month relationship (or whatever they “were”) was reason enough to treat Sophie with zero respect. But you shouldn’t need a label to show someone basic courtesy. The murky state of communication we’ve grown to accept — coupled with the who-ever-cares-less dynamic — is the downfall of college dating today. Even when it’s casual, sex is not a game with a winner and a loser. When played like that, nobody wins.

#The Sexual Spectrum

I was never willing to stand shivering outside a final club just so I could compete with other girls for the chance to binge-drink and sleep with someone random because he was connected. So I looked for romantic prospects elsewhere — my dorm, in class, and through extracurriculars. Many of my girl friends felt the same, so we found ourselves gravitating toward more artsy circles, attracted to guys who might be characterized as sensitive or artistic types. In short, we found ourselves crushing on a lot of gay guys.

Her senior year at Harvard, my best friend, Adie, 23, who is bisexual, had a crush on Paul, who is also bisexual...in addition to being smart and sexy. Paul’s friends told Adie that he was “really into” her, so she asked him out for drinks and he said yes. They went out and had a blast. When the date was over, it was pouring on Cambridge’s cobblestone streets, so Paul offered for Adie to stay over...except he refused even to touch her when they got into bed. She didn’t want to seem “overly interested,” so she decided not to ask Paul for any kind of explanation.

Over the next few weeks, Adie tried to get Paul to hang out again, but he would give her only what she called a vaguely positive response, saying things like, “Yeah, for sure. Soon?” Adie recalls. “Paul gave me enough to think that I had a small chance but also made me feel like I was being pushy every time I asked him to hang out.” Adie started feeling self-conscious about how much more she seemed to care.

Lucky for Adie, she realized after a month that she thought Paul’s straight friend Greg was hotter anyway, and so she hit on him at a party one Friday night. At the end of the night, Greg asked her to go to dinner on Saturday. After a great date with Greg, Adie received an angry text from Paul: “It’s really messed up that you went on a date with my best friend. You led me on.” Adie told him that was unfair and that actually she was led on by him. Paul apologized: “Sorry, I’m just in a weird place right now — sexually and emotionally.” So who cared less? It’s not clear, but Adie found out months later through mutual friends that Paul had been in love with Greg the whole time. So that was the end of Adie and Paul, Adie and Greg — and possibly Paul and Greg.

Stories like this are strikingly common because now more than ever, it’s acceptable and even cool for college kids to be open to sexual experimentation or identify as having a fluid sexuality that doesn’t fit the neat binary of gay and straight.

Overall, this is a great thing. Humans are complicated beings — so it makes sense that our sexuality is complicated too. That said, I also believe that the cultural acceptance of the gradient between gay and straight has made the terrain of college dating a bit rockier and often downright confusing. None of this is an issue of people being gay or straight. It’s about adding one more element to the mix that potentially complicates dating and communicating about dating.

Just the other day, I was catching up with Annie, 22, a friend from college. Naturally, we got to the subject of dating and began talking about a guy named Jay, whom she was hooking up with in school. To us, Jay seemed straight, albeit one of those straight guys who had a notable number of gay and bi male friends. But one night when they were “dating,” Jay casually told Annie that the weekend before, one of his gay friends suggested they hook up. “And so Jay told me that he fucked his friend,” Annie recalls, “and that he would do it again.” Annie expressed nothing more than mild amusement, but if I were her, I’d definitively have been hurt. Not simply because Jay had sex with a man but also because I would’ve wanted to know about his desire to experiment rather than be told retroactively and in such a casual way. This kind of sexual fluidity adds yet another gray area to college dating, and it’s usually in the gray areas where people get hurt — be it because of the vagueness of texting and Gchatting, the whoever-cares-less- wins dynamic, or because someone you thought was into you just had casual sex with his best guy friend.

#Learning to Care

I don’t offer up these anecdotes to point to some bleak future for all college-age women looking for love and sex on campus. The world is changing, and I don’t believe we should feel nostalgic for the kind of romance mourned by Donna Freitas, PhD, in The End of Sex: How Hookup Culture Is Leaving a Generation Unhappy, Sexually Unfulfilled, and Confused About Intimacy. But we should be working to achieve the end of the whoever-cares-less-wins game (and not The End of Men). Sure, caring less brings with it a kind of security. By never making yourself vulnerable, you are automatically protected against rejection. But that type of security is nothing more than glorified loneliness. You’re closing doors to the kinds of experiences and emotions that arise from caring deeply about another person.

Once we stop playing games, ditch the defense mechanism of apathy, and quit communicating with emoticons, we will be much better off when it comes to dating.

I had the chance to test this theory when I had my own dating epiphany in college. For three years, I was addicted to making vague nonplans and finding new ways to put up emotional walls in order to avoid getting hurt. All that pretending not to care led to many midnight bowls of cereal and very few dates, and it left me feeling deficient and scared, wondering how I’d ever learn to let down my guard and whether I would ever experience anything like true intimacy.

Ironically, it was right after the Nate debacle my senior year that I began dating a guy named Dean. We had been friends first, and when our friendship turned into more, I felt honest with him, honest with myself — and terrifyingly, emotionally vulnerable. For the first time, there was not a single cell in me that was concerned with how to care less. We dated happily for a year.

For most of my college career, I was dead wrong about dating, and so were most of my friends. Acting unaffected doesn’t give you power, and communicating as vaguely as possible doesn’t give you the upper hand. It’s time to speak in full sentences, not emoji. It’s time to demand to be treated with respect — which means women should stop lining up like cattle outside Harvard’s final clubs and fraternities across the country. It’s time to stop playing by the rules of whoever cares less wins. Because nobody will ever win, and relationships (heck, even hookups) are no fun when they're just a game.
